language: node_js
node_js:
- '6'
services:
- mongodb
cache:
  directories:
    - node_modules
    
 script:
  - npm run serve
  - npm test
  
 before_deploy:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip
  
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY 
    local_dir: dpl_cd_upload
    skip_cleanup: true
    on: &2
      repo: KarthigaaM/express
    bucket: express-app
    region: us-east-2

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: express-app
    key: latest.zip
    bundle_type: zip
    application: express
    deployment_group: expressapp-group
    region: us-east-2
    on: *2

