language: node_js
node_js:
- '6'
services:
- mongodb
cache:
  directories:
    - node_modules
deploy:
- provider: s3
  access_key_id:AKIAJ5JZ7EGL5XBZQQQQ
  secret_access_key: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 
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: organization/reponameHERE
  bucket: express-app
  region: us-east-2
- provider: codedeploy
  access_key_id: AKIAJ5JZ7EGL5XBZQQQQ
  secret_access_key: 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
  bucket: express-app
  key: latest.zip
  bundle_type: zip
  application: express
  deployment_group: expressapp-group
  region: serverRegionHERE
  on: *2
script:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip
